package com.applemango.SteveJobda.db.generate.dao;

import com.applemango.SteveJobda.db.generate.model.AdminAuth;
import com.applemango.SteveJobda.db.generate.model.AdminAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    long countByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int deleteByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int deleteByPrimaryKey(Integer adminAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int insert(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int insertSelective(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    List<AdminAuth> selectByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    AdminAuth selectByPrimaryKey(Integer adminAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int updateByExampleSelective(@Param("row") AdminAuth row, @Param("example") AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int updateByExample(@Param("row") AdminAuth row, @Param("example") AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int updateByPrimaryKeySelective(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    int updateByPrimaryKey(AdminAuth row);
}