package com.applemango.SteveJobda.db.generate.dao;

import com.applemango.SteveJobda.db.generate.model.Auth;
import com.applemango.SteveJobda.db.generate.model.AuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    long countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int deleteByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int insert(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int insertSelective(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    Auth selectByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int updateByExampleSelective(@Param("row") Auth row, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int updateByExample(@Param("row") Auth row, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int updateByPrimaryKeySelective(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    int updateByPrimaryKey(Auth row);
}