package com.applemango.SteveJobda.db.generate.dao;

import com.applemango.SteveJobda.db.generate.model.Posting;
import com.applemango.SteveJobda.db.generate.model.PostingExample;
import com.applemango.SteveJobda.db.generate.model.PostingWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    long countByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int deleteByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int deleteByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int insert(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int insertSelective(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    List<PostingWithBLOBs> selectByExampleWithBLOBs(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    List<Posting> selectByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    PostingWithBLOBs selectByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByExampleSelective(@Param("row") PostingWithBLOBs row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") PostingWithBLOBs row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByExample(@Param("row") Posting row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByPrimaryKeySelective(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 15 15:29:13 KST 2023
     */
    int updateByPrimaryKey(Posting row);
}