package com.applemango.SteveJobda.db.generate.dao;

import com.applemango.SteveJobda.db.generate.model.UserAuth;
import com.applemango.SteveJobda.db.generate.model.UserAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    long countByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int deleteByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int deleteByPrimaryKey(Integer userAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int insert(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int insertSelective(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    List<UserAuth> selectByExample(UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    UserAuth selectByPrimaryKey(Integer userAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int updateByExampleSelective(@Param("row") UserAuth row, @Param("example") UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int updateByExample(@Param("row") UserAuth row, @Param("example") UserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int updateByPrimaryKeySelective(UserAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    int updateByPrimaryKey(UserAuth row);
}