package com.applemango.SteveJobda.domain;

import java.io.Serializable;
import java.util.Date;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.pw
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String pw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.team
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date updatedDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Boolean deleteYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_sn
     *
     * @return the value of admin.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_sn
     *
     * @param adminSn the value for admin.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.pw
     *
     * @return the value of admin.pw
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.pw
     *
     * @param pw the value for admin.pw
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.team
     *
     * @return the value of admin.team
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.team
     *
     * @param team the value for admin.team
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_datetime
     *
     * @return the value of admin.create_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_datetime
     *
     * @param createDatetime the value for admin.create_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.updated_datetime
     *
     * @return the value of admin.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.updated_datetime
     *
     * @param updatedDatetime the value for admin.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.delete_yn
     *
     * @return the value of admin.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Boolean getDeleteYn() {
        return deleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.delete_yn
     *
     * @param deleteYn the value for admin.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setDeleteYn(Boolean deleteYn) {
        this.deleteYn = deleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminSn=").append(adminSn);
        sb.append(", id=").append(id);
        sb.append(", pw=").append(pw);
        sb.append(", name=").append(name);
        sb.append(", team=").append(team);
        sb.append(", phone=").append(phone);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", updatedDatetime=").append(updatedDatetime);
        sb.append(", deleteYn=").append(deleteYn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admin other = (Admin) that;
        return (this.getAdminSn() == null ? other.getAdminSn() == null : this.getAdminSn().equals(other.getAdminSn()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPw() == null ? other.getPw() == null : this.getPw().equals(other.getPw()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTeam() == null ? other.getTeam() == null : this.getTeam().equals(other.getTeam()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()))
            && (this.getUpdatedDatetime() == null ? other.getUpdatedDatetime() == null : this.getUpdatedDatetime().equals(other.getUpdatedDatetime()))
            && (this.getDeleteYn() == null ? other.getDeleteYn() == null : this.getDeleteYn().equals(other.getDeleteYn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdminSn() == null) ? 0 : getAdminSn().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPw() == null) ? 0 : getPw().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTeam() == null) ? 0 : getTeam().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        result = prime * result + ((getUpdatedDatetime() == null) ? 0 : getUpdatedDatetime().hashCode());
        result = prime * result + ((getDeleteYn() == null) ? 0 : getDeleteYn().hashCode());
        return result;
    }
}