package com.applemango.SteveJobda.domain;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_sn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.pw
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private String pw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.name
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.team
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.phone
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.updated_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private Date updatedDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.delete_yn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    private Boolean deleteYn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_sn
     *
     * @return the value of admin.admin_sn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_sn
     *
     * @param adminSn the value for admin.admin_sn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.pw
     *
     * @return the value of admin.pw
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.pw
     *
     * @param pw the value for admin.pw
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.team
     *
     * @return the value of admin.team
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.team
     *
     * @param team the value for admin.team
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.phone
     *
     * @return the value of admin.phone
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.phone
     *
     * @param phone the value for admin.phone
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_datetime
     *
     * @return the value of admin.create_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_datetime
     *
     * @param createDatetime the value for admin.create_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.updated_datetime
     *
     * @return the value of admin.updated_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.updated_datetime
     *
     * @param updatedDatetime the value for admin.updated_datetime
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.delete_yn
     *
     * @return the value of admin.delete_yn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public Boolean getDeleteYn() {
        return deleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.delete_yn
     *
     * @param deleteYn the value for admin.delete_yn
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    public void setDeleteYn(Boolean deleteYn) {
        this.deleteYn = deleteYn;
    }
}