package com.applemango.SteveJobda.domain;

import java.io.Serializable;

public class AdminAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer adminAuthSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer authSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_auth_sn
     *
     * @return the value of admin_auth.admin_auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getAdminAuthSn() {
        return adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_auth_sn
     *
     * @param adminAuthSn the value for admin_auth.admin_auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setAdminAuthSn(Integer adminAuthSn) {
        this.adminAuthSn = adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_sn
     *
     * @return the value of admin_auth.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_sn
     *
     * @param adminSn the value for admin_auth.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.auth_sn
     *
     * @return the value of admin_auth.auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getAuthSn() {
        return authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.auth_sn
     *
     * @param authSn the value for admin_auth.auth_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setAuthSn(Integer authSn) {
        this.authSn = authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminAuthSn=").append(adminAuthSn);
        sb.append(", adminSn=").append(adminSn);
        sb.append(", authSn=").append(authSn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminAuth other = (AdminAuth) that;
        return (this.getAdminAuthSn() == null ? other.getAdminAuthSn() == null : this.getAdminAuthSn().equals(other.getAdminAuthSn()))
            && (this.getAdminSn() == null ? other.getAdminSn() == null : this.getAdminSn().equals(other.getAdminSn()))
            && (this.getAuthSn() == null ? other.getAuthSn() == null : this.getAuthSn().equals(other.getAuthSn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdminAuthSn() == null) ? 0 : getAdminAuthSn().hashCode());
        result = prime * result + ((getAdminSn() == null) ? 0 : getAdminSn().hashCode());
        result = prime * result + ((getAuthSn() == null) ? 0 : getAuthSn().hashCode());
        return result;
    }
}