package com.applemango.SteveJobda.domain;

public class AdminAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    private Integer adminAuthSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    private Integer authSn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_auth_sn
     *
     * @return the value of admin_auth.admin_auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public Integer getAdminAuthSn() {
        return adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_auth_sn
     *
     * @param adminAuthSn the value for admin_auth.admin_auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public void setAdminAuthSn(Integer adminAuthSn) {
        this.adminAuthSn = adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_sn
     *
     * @return the value of admin_auth.admin_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_sn
     *
     * @param adminSn the value for admin_auth.admin_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.auth_sn
     *
     * @return the value of admin_auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public Integer getAuthSn() {
        return authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.auth_sn
     *
     * @param authSn the value for admin_auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    public void setAuthSn(Integer authSn) {
        this.authSn = authSn;
    }
}