package com.applemango.SteveJobda.domain;

import java.io.Serializable;

public class Auth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    private Integer authSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.type
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.auth_sn
     *
     * @return the value of auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    public Integer getAuthSn() {
        return authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.auth_sn
     *
     * @param authSn the value for auth.auth_sn
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    public void setAuthSn(Integer authSn) {
        this.authSn = authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.type
     *
     * @return the value of auth.type
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.type
     *
     * @param type the value for auth.type
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authSn=").append(authSn);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Auth other = (Auth) that;
        return (this.getAuthSn() == null ? other.getAuthSn() == null : this.getAuthSn().equals(other.getAuthSn()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAuthSn() == null) ? 0 : getAuthSn().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }
}