package com.applemango.SteveJobda.domain;

import java.io.Serializable;

public class Img implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer imgSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.path
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.file_name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.width
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.height
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table img
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.img_sn
     *
     * @return the value of img.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getImgSn() {
        return imgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.img_sn
     *
     * @param imgSn the value for img.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setImgSn(Integer imgSn) {
        this.imgSn = imgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.path
     *
     * @return the value of img.path
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.path
     *
     * @param path the value for img.path
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.file_name
     *
     * @return the value of img.file_name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.file_name
     *
     * @param fileName the value for img.file_name
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.width
     *
     * @return the value of img.width
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.width
     *
     * @param width the value for img.width
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.height
     *
     * @return the value of img.height
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.height
     *
     * @param height the value for img.height
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", imgSn=").append(imgSn);
        sb.append(", path=").append(path);
        sb.append(", fileName=").append(fileName);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Img other = (Img) that;
        return (this.getImgSn() == null ? other.getImgSn() == null : this.getImgSn().equals(other.getImgSn()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getWidth() == null ? other.getWidth() == null : this.getWidth().equals(other.getWidth()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getImgSn() == null) ? 0 : getImgSn().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getWidth() == null) ? 0 : getWidth().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        return result;
    }
}