package com.applemango.SteveJobda.domain;

import java.io.Serializable;

public class PostingWithBLOBs extends Posting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.detail
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.qualification
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.detail
     *
     * @return the value of posting.detail
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.detail
     *
     * @param detail the value for posting.detail
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.qualification
     *
     * @return the value of posting.qualification
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.qualification
     *
     * @param qualification the value for posting.qualification
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", detail=").append(detail);
        sb.append(", qualification=").append(qualification);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PostingWithBLOBs other = (PostingWithBLOBs) that;
        return (this.getPostingSn() == null ? other.getPostingSn() == null : this.getPostingSn().equals(other.getPostingSn()))
            && (this.getAdminSn() == null ? other.getAdminSn() == null : this.getAdminSn().equals(other.getAdminSn()))
            && (this.getImgSn() == null ? other.getImgSn() == null : this.getImgSn().equals(other.getImgSn()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getStartDatetime() == null ? other.getStartDatetime() == null : this.getStartDatetime().equals(other.getStartDatetime()))
            && (this.getEndDatetime() == null ? other.getEndDatetime() == null : this.getEndDatetime().equals(other.getEndDatetime()))
            && (this.getCreatedDatetime() == null ? other.getCreatedDatetime() == null : this.getCreatedDatetime().equals(other.getCreatedDatetime()))
            && (this.getUpdatedDatetime() == null ? other.getUpdatedDatetime() == null : this.getUpdatedDatetime().equals(other.getUpdatedDatetime()))
            && (this.getDeleteYn() == null ? other.getDeleteYn() == null : this.getDeleteYn().equals(other.getDeleteYn()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
            && (this.getQualification() == null ? other.getQualification() == null : this.getQualification().equals(other.getQualification()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPostingSn() == null) ? 0 : getPostingSn().hashCode());
        result = prime * result + ((getAdminSn() == null) ? 0 : getAdminSn().hashCode());
        result = prime * result + ((getImgSn() == null) ? 0 : getImgSn().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getStartDatetime() == null) ? 0 : getStartDatetime().hashCode());
        result = prime * result + ((getEndDatetime() == null) ? 0 : getEndDatetime().hashCode());
        result = prime * result + ((getCreatedDatetime() == null) ? 0 : getCreatedDatetime().hashCode());
        result = prime * result + ((getUpdatedDatetime() == null) ? 0 : getUpdatedDatetime().hashCode());
        result = prime * result + ((getDeleteYn() == null) ? 0 : getDeleteYn().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((getQualification() == null) ? 0 : getQualification().hashCode());
        return result;
    }
}