package com.applemango.SteveJobda.domain;

import java.io.Serializable;
import java.util.Date;

public class Posting implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.posting_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer postingSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Integer imgSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.title
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.start_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date startDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.end_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date endDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.created_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Date updatedDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private Boolean deleteYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.posting_sn
     *
     * @return the value of posting.posting_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getPostingSn() {
        return postingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.posting_sn
     *
     * @param postingSn the value for posting.posting_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setPostingSn(Integer postingSn) {
        this.postingSn = postingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.admin_sn
     *
     * @return the value of posting.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.admin_sn
     *
     * @param adminSn the value for posting.admin_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.img_sn
     *
     * @return the value of posting.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Integer getImgSn() {
        return imgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.img_sn
     *
     * @param imgSn the value for posting.img_sn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setImgSn(Integer imgSn) {
        this.imgSn = imgSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.title
     *
     * @return the value of posting.title
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.title
     *
     * @param title the value for posting.title
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.start_datetime
     *
     * @return the value of posting.start_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getStartDatetime() {
        return startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.start_datetime
     *
     * @param startDatetime the value for posting.start_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.end_datetime
     *
     * @return the value of posting.end_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.end_datetime
     *
     * @param endDatetime the value for posting.end_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.created_datetime
     *
     * @return the value of posting.created_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.created_datetime
     *
     * @param createdDatetime the value for posting.created_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.updated_datetime
     *
     * @return the value of posting.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.updated_datetime
     *
     * @param updatedDatetime the value for posting.updated_datetime
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.delete_yn
     *
     * @return the value of posting.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public Boolean getDeleteYn() {
        return deleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.delete_yn
     *
     * @param deleteYn the value for posting.delete_yn
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    public void setDeleteYn(Boolean deleteYn) {
        this.deleteYn = deleteYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", postingSn=").append(postingSn);
        sb.append(", adminSn=").append(adminSn);
        sb.append(", imgSn=").append(imgSn);
        sb.append(", title=").append(title);
        sb.append(", startDatetime=").append(startDatetime);
        sb.append(", endDatetime=").append(endDatetime);
        sb.append(", createdDatetime=").append(createdDatetime);
        sb.append(", updatedDatetime=").append(updatedDatetime);
        sb.append(", deleteYn=").append(deleteYn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Posting other = (Posting) that;
        return (this.getPostingSn() == null ? other.getPostingSn() == null : this.getPostingSn().equals(other.getPostingSn()))
            && (this.getAdminSn() == null ? other.getAdminSn() == null : this.getAdminSn().equals(other.getAdminSn()))
            && (this.getImgSn() == null ? other.getImgSn() == null : this.getImgSn().equals(other.getImgSn()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getStartDatetime() == null ? other.getStartDatetime() == null : this.getStartDatetime().equals(other.getStartDatetime()))
            && (this.getEndDatetime() == null ? other.getEndDatetime() == null : this.getEndDatetime().equals(other.getEndDatetime()))
            && (this.getCreatedDatetime() == null ? other.getCreatedDatetime() == null : this.getCreatedDatetime().equals(other.getCreatedDatetime()))
            && (this.getUpdatedDatetime() == null ? other.getUpdatedDatetime() == null : this.getUpdatedDatetime().equals(other.getUpdatedDatetime()))
            && (this.getDeleteYn() == null ? other.getDeleteYn() == null : this.getDeleteYn().equals(other.getDeleteYn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPostingSn() == null) ? 0 : getPostingSn().hashCode());
        result = prime * result + ((getAdminSn() == null) ? 0 : getAdminSn().hashCode());
        result = prime * result + ((getImgSn() == null) ? 0 : getImgSn().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getStartDatetime() == null) ? 0 : getStartDatetime().hashCode());
        result = prime * result + ((getEndDatetime() == null) ? 0 : getEndDatetime().hashCode());
        result = prime * result + ((getCreatedDatetime() == null) ? 0 : getCreatedDatetime().hashCode());
        result = prime * result + ((getUpdatedDatetime() == null) ? 0 : getUpdatedDatetime().hashCode());
        result = prime * result + ((getDeleteYn() == null) ? 0 : getDeleteYn().hashCode());
        return result;
    }
}