package com.applemango.SteveJobda.db.generate.model;

public class AdminAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    private Integer adminAuthSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.admin_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    private Integer adminSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_auth.auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    private Integer authSn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_auth_sn
     *
     * @return the value of admin_auth.admin_auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public Integer getAdminAuthSn() {
        return adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public AdminAuth withAdminAuthSn(Integer adminAuthSn) {
        this.setAdminAuthSn(adminAuthSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_auth_sn
     *
     * @param adminAuthSn the value for admin_auth.admin_auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public void setAdminAuthSn(Integer adminAuthSn) {
        this.adminAuthSn = adminAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.admin_sn
     *
     * @return the value of admin_auth.admin_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public Integer getAdminSn() {
        return adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public AdminAuth withAdminSn(Integer adminSn) {
        this.setAdminSn(adminSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.admin_sn
     *
     * @param adminSn the value for admin_auth.admin_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public void setAdminSn(Integer adminSn) {
        this.adminSn = adminSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_auth.auth_sn
     *
     * @return the value of admin_auth.auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public Integer getAuthSn() {
        return authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public AdminAuth withAuthSn(Integer authSn) {
        this.setAuthSn(authSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_auth.auth_sn
     *
     * @param authSn the value for admin_auth.auth_sn
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    public void setAuthSn(Integer authSn) {
        this.authSn = authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Wed Jun 14 14:15:42 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminAuthSn=").append(adminAuthSn);
        sb.append(", adminSn=").append(adminSn);
        sb.append(", authSn=").append(authSn);
        sb.append("]");
        return sb.toString();
    }
}