package com.applemango.SteveJobda.db.generate.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public PostingExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostingSnIsNull() {
            addCriterion("posting_sn is null");
            return (Criteria) this;
        }

        public Criteria andPostingSnIsNotNull() {
            addCriterion("posting_sn is not null");
            return (Criteria) this;
        }

        public Criteria andPostingSnEqualTo(Integer value) {
            addCriterion("posting_sn =", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnNotEqualTo(Integer value) {
            addCriterion("posting_sn <>", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnGreaterThan(Integer value) {
            addCriterion("posting_sn >", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("posting_sn >=", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnLessThan(Integer value) {
            addCriterion("posting_sn <", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnLessThanOrEqualTo(Integer value) {
            addCriterion("posting_sn <=", value, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnIn(List<Integer> values) {
            addCriterion("posting_sn in", values, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnNotIn(List<Integer> values) {
            addCriterion("posting_sn not in", values, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnBetween(Integer value1, Integer value2) {
            addCriterion("posting_sn between", value1, value2, "postingSn");
            return (Criteria) this;
        }

        public Criteria andPostingSnNotBetween(Integer value1, Integer value2) {
            addCriterion("posting_sn not between", value1, value2, "postingSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnIsNull() {
            addCriterion("admin_sn is null");
            return (Criteria) this;
        }

        public Criteria andAdminSnIsNotNull() {
            addCriterion("admin_sn is not null");
            return (Criteria) this;
        }

        public Criteria andAdminSnEqualTo(Integer value) {
            addCriterion("admin_sn =", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnNotEqualTo(Integer value) {
            addCriterion("admin_sn <>", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnGreaterThan(Integer value) {
            addCriterion("admin_sn >", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin_sn >=", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnLessThan(Integer value) {
            addCriterion("admin_sn <", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnLessThanOrEqualTo(Integer value) {
            addCriterion("admin_sn <=", value, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnIn(List<Integer> values) {
            addCriterion("admin_sn in", values, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnNotIn(List<Integer> values) {
            addCriterion("admin_sn not in", values, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnBetween(Integer value1, Integer value2) {
            addCriterion("admin_sn between", value1, value2, "adminSn");
            return (Criteria) this;
        }

        public Criteria andAdminSnNotBetween(Integer value1, Integer value2) {
            addCriterion("admin_sn not between", value1, value2, "adminSn");
            return (Criteria) this;
        }

        public Criteria andImgSnIsNull() {
            addCriterion("img_sn is null");
            return (Criteria) this;
        }

        public Criteria andImgSnIsNotNull() {
            addCriterion("img_sn is not null");
            return (Criteria) this;
        }

        public Criteria andImgSnEqualTo(Integer value) {
            addCriterion("img_sn =", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnNotEqualTo(Integer value) {
            addCriterion("img_sn <>", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnGreaterThan(Integer value) {
            addCriterion("img_sn >", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("img_sn >=", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnLessThan(Integer value) {
            addCriterion("img_sn <", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnLessThanOrEqualTo(Integer value) {
            addCriterion("img_sn <=", value, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnIn(List<Integer> values) {
            addCriterion("img_sn in", values, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnNotIn(List<Integer> values) {
            addCriterion("img_sn not in", values, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnBetween(Integer value1, Integer value2) {
            addCriterion("img_sn between", value1, value2, "imgSn");
            return (Criteria) this;
        }

        public Criteria andImgSnNotBetween(Integer value1, Integer value2) {
            addCriterion("img_sn not between", value1, value2, "imgSn");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeIsNull() {
            addCriterion("start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeIsNotNull() {
            addCriterion("start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeEqualTo(Date value) {
            addCriterion("start_datetime =", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeNotEqualTo(Date value) {
            addCriterion("start_datetime <>", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeGreaterThan(Date value) {
            addCriterion("start_datetime >", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_datetime >=", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeLessThan(Date value) {
            addCriterion("start_datetime <", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("start_datetime <=", value, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeIn(List<Date> values) {
            addCriterion("start_datetime in", values, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeNotIn(List<Date> values) {
            addCriterion("start_datetime not in", values, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeBetween(Date value1, Date value2) {
            addCriterion("start_datetime between", value1, value2, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andStartDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("start_datetime not between", value1, value2, "startDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIsNull() {
            addCriterion("end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIsNotNull() {
            addCriterion("end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeEqualTo(Date value) {
            addCriterion("end_datetime =", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotEqualTo(Date value) {
            addCriterion("end_datetime <>", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeGreaterThan(Date value) {
            addCriterion("end_datetime >", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_datetime >=", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeLessThan(Date value) {
            addCriterion("end_datetime <", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("end_datetime <=", value, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeIn(List<Date> values) {
            addCriterion("end_datetime in", values, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotIn(List<Date> values) {
            addCriterion("end_datetime not in", values, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeBetween(Date value1, Date value2) {
            addCriterion("end_datetime between", value1, value2, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andEndDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("end_datetime not between", value1, value2, "endDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeIsNull() {
            addCriterion("created_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeIsNotNull() {
            addCriterion("created_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeEqualTo(Date value) {
            addCriterion("created_datetime =", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeNotEqualTo(Date value) {
            addCriterion("created_datetime <>", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeGreaterThan(Date value) {
            addCriterion("created_datetime >", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_datetime >=", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeLessThan(Date value) {
            addCriterion("created_datetime <", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("created_datetime <=", value, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeIn(List<Date> values) {
            addCriterion("created_datetime in", values, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeNotIn(List<Date> values) {
            addCriterion("created_datetime not in", values, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeBetween(Date value1, Date value2) {
            addCriterion("created_datetime between", value1, value2, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andCreatedDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("created_datetime not between", value1, value2, "createdDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeIsNull() {
            addCriterion("updated_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeIsNotNull() {
            addCriterion("updated_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeEqualTo(Date value) {
            addCriterion("updated_datetime =", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeNotEqualTo(Date value) {
            addCriterion("updated_datetime <>", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeGreaterThan(Date value) {
            addCriterion("updated_datetime >", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_datetime >=", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeLessThan(Date value) {
            addCriterion("updated_datetime <", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_datetime <=", value, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeIn(List<Date> values) {
            addCriterion("updated_datetime in", values, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeNotIn(List<Date> values) {
            addCriterion("updated_datetime not in", values, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeBetween(Date value1, Date value2) {
            addCriterion("updated_datetime between", value1, value2, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatedDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_datetime not between", value1, value2, "updatedDatetime");
            return (Criteria) this;
        }

        public Criteria andDeleteYnIsNull() {
            addCriterion("delete_yn is null");
            return (Criteria) this;
        }

        public Criteria andDeleteYnIsNotNull() {
            addCriterion("delete_yn is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteYnEqualTo(Boolean value) {
            addCriterion("delete_yn =", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnNotEqualTo(Boolean value) {
            addCriterion("delete_yn <>", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnGreaterThan(Boolean value) {
            addCriterion("delete_yn >", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_yn >=", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnLessThan(Boolean value) {
            addCriterion("delete_yn <", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_yn <=", value, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnIn(List<Boolean> values) {
            addCriterion("delete_yn in", values, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnNotIn(List<Boolean> values) {
            addCriterion("delete_yn not in", values, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_yn between", value1, value2, "deleteYn");
            return (Criteria) this;
        }

        public Criteria andDeleteYnNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_yn not between", value1, value2, "deleteYn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posting
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 13 08:52:40 KST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table posting
     *
     * @mbg.generated Tue Jun 13 08:52:40 KST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}