package com.applemango.SteveJobda.db.generate.model;

import java.util.ArrayList;
import java.util.List;

public class UserAuthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public UserAuthExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserAuthSnIsNull() {
            addCriterion("user_auth_sn is null");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnIsNotNull() {
            addCriterion("user_auth_sn is not null");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnEqualTo(Integer value) {
            addCriterion("user_auth_sn =", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnNotEqualTo(Integer value) {
            addCriterion("user_auth_sn <>", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnGreaterThan(Integer value) {
            addCriterion("user_auth_sn >", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_auth_sn >=", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnLessThan(Integer value) {
            addCriterion("user_auth_sn <", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnLessThanOrEqualTo(Integer value) {
            addCriterion("user_auth_sn <=", value, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnIn(List<Integer> values) {
            addCriterion("user_auth_sn in", values, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnNotIn(List<Integer> values) {
            addCriterion("user_auth_sn not in", values, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnBetween(Integer value1, Integer value2) {
            addCriterion("user_auth_sn between", value1, value2, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserAuthSnNotBetween(Integer value1, Integer value2) {
            addCriterion("user_auth_sn not between", value1, value2, "userAuthSn");
            return (Criteria) this;
        }

        public Criteria andUserSnIsNull() {
            addCriterion("user_sn is null");
            return (Criteria) this;
        }

        public Criteria andUserSnIsNotNull() {
            addCriterion("user_sn is not null");
            return (Criteria) this;
        }

        public Criteria andUserSnEqualTo(Integer value) {
            addCriterion("user_sn =", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnNotEqualTo(Integer value) {
            addCriterion("user_sn <>", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnGreaterThan(Integer value) {
            addCriterion("user_sn >", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_sn >=", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnLessThan(Integer value) {
            addCriterion("user_sn <", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnLessThanOrEqualTo(Integer value) {
            addCriterion("user_sn <=", value, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnIn(List<Integer> values) {
            addCriterion("user_sn in", values, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnNotIn(List<Integer> values) {
            addCriterion("user_sn not in", values, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnBetween(Integer value1, Integer value2) {
            addCriterion("user_sn between", value1, value2, "userSn");
            return (Criteria) this;
        }

        public Criteria andUserSnNotBetween(Integer value1, Integer value2) {
            addCriterion("user_sn not between", value1, value2, "userSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnIsNull() {
            addCriterion("auth_sn is null");
            return (Criteria) this;
        }

        public Criteria andAuthSnIsNotNull() {
            addCriterion("auth_sn is not null");
            return (Criteria) this;
        }

        public Criteria andAuthSnEqualTo(Integer value) {
            addCriterion("auth_sn =", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnNotEqualTo(Integer value) {
            addCriterion("auth_sn <>", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnGreaterThan(Integer value) {
            addCriterion("auth_sn >", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("auth_sn >=", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnLessThan(Integer value) {
            addCriterion("auth_sn <", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnLessThanOrEqualTo(Integer value) {
            addCriterion("auth_sn <=", value, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnIn(List<Integer> values) {
            addCriterion("auth_sn in", values, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnNotIn(List<Integer> values) {
            addCriterion("auth_sn not in", values, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnBetween(Integer value1, Integer value2) {
            addCriterion("auth_sn between", value1, value2, "authSn");
            return (Criteria) this;
        }

        public Criteria andAuthSnNotBetween(Integer value1, Integer value2) {
            addCriterion("auth_sn not between", value1, value2, "authSn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 15 09:14:15 KST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}