package com.applemango.SteveJobda.db.generate.model;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    private Integer userAuthSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    private Integer userSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    private Integer authSn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_auth_sn
     *
     * @return the value of user_auth.user_auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public Integer getUserAuthSn() {
        return userAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public UserAuth withUserAuthSn(Integer userAuthSn) {
        this.setUserAuthSn(userAuthSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_auth_sn
     *
     * @param userAuthSn the value for user_auth.user_auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void setUserAuthSn(Integer userAuthSn) {
        this.userAuthSn = userAuthSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_sn
     *
     * @return the value of user_auth.user_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public Integer getUserSn() {
        return userSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public UserAuth withUserSn(Integer userSn) {
        this.setUserSn(userSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_sn
     *
     * @param userSn the value for user_auth.user_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void setUserSn(Integer userSn) {
        this.userSn = userSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_sn
     *
     * @return the value of user_auth.auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public Integer getAuthSn() {
        return authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public UserAuth withAuthSn(Integer authSn) {
        this.setAuthSn(authSn);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_sn
     *
     * @param authSn the value for user_auth.auth_sn
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    public void setAuthSn(Integer authSn) {
        this.authSn = authSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated Thu Jun 15 09:14:15 KST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userAuthSn=").append(userAuthSn);
        sb.append(", userSn=").append(userSn);
        sb.append(", authSn=").append(authSn);
        sb.append("]");
        return sb.toString();
    }
}