package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.AdminAuth;
import com.applemango.SteveJobda.domain.AdminAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdminAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    long countByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int deleteByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int deleteByPrimaryKey(Integer adminAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int insert(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int insertSelective(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<AdminAuth> selectByExampleWithRowbounds(AdminAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<AdminAuth> selectByExample(AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    AdminAuth selectByPrimaryKey(Integer adminAuthSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByExampleSelective(@Param("row") AdminAuth row, @Param("example") AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByExample(@Param("row") AdminAuth row, @Param("example") AdminAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByPrimaryKeySelective(AdminAuth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_auth
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByPrimaryKey(AdminAuth row);
}