package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Admin;
import com.applemango.SteveJobda.domain.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int deleteByPrimaryKey(Integer adminSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int insert(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int insertSelective(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    List<Admin> selectByExampleWithRowbounds(AdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    Admin selectByPrimaryKey(Integer adminSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByExampleSelective(@Param("row") Admin row, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByExample(@Param("row") Admin row, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByPrimaryKeySelective(Admin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByPrimaryKey(Admin row);
}