package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Admin;
import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    int deleteByPrimaryKey(Integer adminSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    Admin selectByPrimaryKey(Integer adminSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    List<Admin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Jun 08 12:05:30 KST 2023
     */
    int updateByPrimaryKey(Admin record);
}