package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Auth;
import java.util.List;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int deleteByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    Auth selectByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    List<Auth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int updateByPrimaryKey(Auth record);
}