package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Auth;
import com.applemango.SteveJobda.domain.AuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    long countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int deleteByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int insert(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int insertSelective(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    List<Auth> selectByExampleWithRowbounds(AuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    Auth selectByPrimaryKey(Integer authSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByExampleSelective(@Param("row") Auth row, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByExample(@Param("row") Auth row, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByPrimaryKeySelective(Auth row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth
     *
     * @mbg.generated Fri Jun 09 09:59:38 KST 2023
     */
    int updateByPrimaryKey(Auth row);
}