package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Img;
import java.util.List;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int deleteByPrimaryKey(Integer imgSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    Img selectByPrimaryKey(Integer imgSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    List<Img> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int updateByPrimaryKey(Img record);
}