package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Posting;
import java.util.List;

public interface PostingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int deleteByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int insert(Posting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    Posting selectByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    List<Posting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 13:58:32 KST 2023
     */
    int updateByPrimaryKey(Posting record);
}