package com.applemango.SteveJobda.persistence.mapper;

import com.applemango.SteveJobda.domain.Posting;
import com.applemango.SteveJobda.domain.PostingExample;
import com.applemango.SteveJobda.domain.PostingWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    long countByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int deleteByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int deleteByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int insert(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int insertSelective(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<PostingWithBLOBs> selectByExampleWithBLOBsWithRowbounds(PostingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<PostingWithBLOBs> selectByExampleWithBLOBs(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<Posting> selectByExampleWithRowbounds(PostingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    List<Posting> selectByExample(PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    PostingWithBLOBs selectByPrimaryKey(Integer postingSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByExampleSelective(@Param("row") PostingWithBLOBs row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") PostingWithBLOBs row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByExample(@Param("row") Posting row, @Param("example") PostingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByPrimaryKeySelective(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PostingWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posting
     *
     * @mbg.generated Thu Jun 08 16:45:53 KST 2023
     */
    int updateByPrimaryKey(Posting row);
}